image: Visual Studio 2022

environment:
  global:
    RANDOM_SEED: 0
  matrix:
    - PYTHON_MAJOR: {{cookiecutter.python_major_version}}
      PYTHON_MINOR: {{cookiecutter.python_minor_version}}

cache:
  - .venv -> poetry.lock

install:
  # Add Python to the PATH
  - set PATH=C:\Python%PYTHON_MAJOR%%PYTHON_MINOR%;%PATH%
  - set PATH=C:\Python%PYTHON_MAJOR%%PYTHON_MINOR%\Scripts;%PATH%
  # Install system dependencies
  - choco install make
  - curl -sSL https://install.python-poetry.org | python -
  - set PATH=%USERPROFILE%\AppData\Roaming\Python\Scripts;%PATH%
  - make doctor
  # Install project dependencies
  - make install

build: off

test_script:
  - make check
  - make test
